import type { AssessmentData } from '../types';

interface SoapNotePageProps {
  data: AssessmentData;
  onBack: () => void;
}

export default function SoapNotePage({ data, onBack }: SoapNotePageProps) {
  
  // A quick hackathon trick to show a functional print/copy feature
  const handlePrint = () => {
    window.print();
  };

  const handleCopy = () => {
    const soapText = `
SUBJECTIVE:
Patient presents with ${data.chiefComplaint} starting ${data.onset.toLowerCase()}. 
Associated symptoms include ${data.associatedSymptoms.toLowerCase()}.

OBJECTIVE:
Vitals: Pending evaluation.
Physical Exam: Pending evaluation.

ASSESSMENT:
${data.clinicalPhrase}.
AI Note: ${data.explanation}

PLAN:
1. Pending physician orders.
    `.trim();
    navigator.clipboard.writeText(soapText);
    alert("SOAP Note copied to clipboard!");
  };

  return (
    <div className="min-h-screen bg-[#f8fafc] flex flex-col font-sans pb-10">
      
      {/* Header */}
      <header className="bg-white px-6 py-5 flex items-center justify-between sticky top-0 z-10 shadow-sm">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 -ml-2 hover:bg-gray-100 rounded-full transition-colors text-gray-600 cursor-pointer">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M19 12H5M12 19l-7-7 7-7"/>
            </svg>
          </button>
          <div className="w-1.5 h-6 bg-[#1e3a8a] rounded-full"></div>
          <h1 className="text-xl font-bold text-gray-900 tracking-tight">Standardized SOAP Note</h1>
        </div>
        
        <div className="flex gap-3">
          <button onClick={handleCopy} className="text-sm font-bold text-[#2563eb] bg-blue-50 px-4 py-2 rounded-lg hover:bg-blue-100 transition-colors cursor-pointer">
            Copy Text
          </button>
          <button onClick={handlePrint} className="text-sm font-bold text-white bg-[#1e3a8a] px-4 py-2 rounded-lg hover:bg-blue-900 transition-colors cursor-pointer">
            Print EMR
          </button>
        </div>
      </header>

      <main className="flex-1 max-w-3xl w-full mx-auto p-4 sm:p-6 mt-4">
        
        {/* Document Container */}
        <div className="bg-white rounded-lg p-8 sm:p-12 shadow-md border border-gray-200">
          
          <div className="border-b border-gray-300 pb-6 mb-6 flex justify-between items-end">
            <div>
              <h2 className="text-3xl font-black text-gray-900 tracking-tight">Clinical Encounter</h2>
              <p className="text-gray-500 font-medium mt-1">Generated by LinguaBridge Health AI</p>
            </div>
            <div className="text-right text-sm text-gray-500 font-medium">
              Date: {new Date().toLocaleDateString()}
            </div>
          </div>

          <div className="space-y-8">
            {/* Subjective */}
            <section>
              <h3 className="text-lg font-bold text-[#1e3a8a] border-b-2 border-blue-100 pb-1 mb-3">S - Subjective</h3>
              <p className="text-gray-800 leading-relaxed text-lg">
                Patient presents with <span className="font-bold">{data.chiefComplaint}</span>. Condition noted to start <span className="font-bold">{data.onset.toLowerCase()}</span>. Patient reports associated symptoms including <span className="font-bold">{data.associatedSymptoms.toLowerCase()}</span>.
              </p>
            </section>

            {/* Objective */}
            <section>
              <h3 className="text-lg font-bold text-[#1e3a8a] border-b-2 border-blue-100 pb-1 mb-3">O - Objective</h3>
              <div className="bg-gray-50 p-4 rounded-md border border-gray-100 text-gray-500 italic">
                Awaiting physical examination and vital signs input from the attending physician.
              </div>
            </section>

            {/* Assessment */}
            <section>
              <h3 className="text-lg font-bold text-[#1e3a8a] border-b-2 border-blue-100 pb-1 mb-3">A - Assessment</h3>
              <p className="text-gray-800 leading-relaxed text-lg font-semibold">
                {data.clinicalPhrase}
              </p>
              <div className="mt-3 bg-[#e6fbf4] border-l-4 border-[#2ccb96] p-3 text-sm text-[#065f46]">
                <span className="font-bold">AI Translation Context:</span> {data.explanation}
              </div>
            </section>

            {/* Plan */}
            <section>
              <h3 className="text-lg font-bold text-[#1e3a8a] border-b-2 border-blue-100 pb-1 mb-3">P - Plan</h3>
              <ul className="list-decimal pl-5 space-y-2 text-gray-800 text-lg">
                <li>Further physical evaluation required.</li>
                <li className="text-gray-400 italic">__________________________________</li>
                <li className="text-gray-400 italic">__________________________________</li>
              </ul>
            </section>
          </div>
          
        </div>
      </main>
    </div>
  );
}